_emotions# theme: jekyll-theme-minimal
# title: <img src="/images/JEAF_Logo_3C.png" alt="JEAF Generator">
title: JEAF Generator
description: JEAF Generator uses UML models to generate code for Spring, REST, Java, JakarataEE, JEE, Hibernate and others

remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jemoji
#  - font-awesome-less

fixed_navbar: top

permalink: pretty

favicon: jeaf-icon_64.png

livereload: true

markdown: kramdown

footer_menu: footer_menu

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      title: " "
      subtitle: " "
      toc_title: "Table of Contents"
      menubar_toc: false
      #menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true

  -
    scope:
      path: "uml-modeling-guide"
    values:
      title: " "
      subtitle: " "
      image: ../../images/share_image.png
      menubar_toc: false
      menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true
      
  -
    scope:
      path: "developer-guide"
    values:
      title: " "
      subtitle: " "
      image: ../../images/share_image.png
      toc_title: "Table of Contents"
      menubar_toc: false
      menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true
      
      
