_emotions# theme: jekyll-theme-minimal
# title: JEAF Generator
description: Bookmark this to keep an eye on my project updates!

remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

fixed_navbar: top

permalink: pretty

favicon: jeaf-icon_64.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      hero_image: ../jeaf_emotions.png
