_emotions# theme: jekyll-theme-minimal
title: JEAF Generator
description: Bookmark this to keep an eye on my project updates!

remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - kramdown-parser-gfm

fixed_navbar: top

permalink: pretty

favicon: jeaf-icon_64.png

markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      title: " "
      subtitle: " "
      menubar_toc: false
      #menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true

  -
    scope:
      path: "uml-modeling-guide"
    values:
      title: " "
      subtitle: " "
      menubar_toc: false
      menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true
      
  -
    scope:
      path: "developer-guide"
    values:
      title: " "
      subtitle: " "
      menubar_toc: false
      menubar: empty_menu
      # show_sidebar: true
      hide_hero: false
      hero_image: ../../images/jeaf_emotions.png
      hero_height: is-fullwidth
      hero_darken: true
      
      
